version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: desafio_postgres
    environment:
      POSTGRES_USER: DesafioDB
      POSTGRES_PASSWORD: SenhaDB
      POSTGRES_DB: desafio_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
